version: "3.9"
services:
  web:
    build: .
    command: bash -c "bin/rails db:prepare && bin/rails server -b 0.0.0.0 -p 3000"
    ports:
      - "3000:3000"
    volumes:
      - ".:/rails"
